export const LightContants = {
  light: {
    backgroundColor: ["white", "white", "rgba(64,180,145,0.2)"],
    tabBarBackgroundColor: "#FFFFFF",
    safeAreaBackgroundColor: "transparent",
    headerBackgroundColor: "#ffffff",
    greenDecorationDotColor: "#AEC687",
    blackDecorationDotColor: "#000000",
    textColor: "black",
    greyTextColor: "#263238",
    backButtonColor: "#40B491",
    cardBackgroundColor: "#FFFFFF",
    cardShadowColor: "#343C41",
    categoryTagBackgroundColor: "#F4F4F4",
    nextButtonColor: "#042628",
  },
  dark: {
    backgroundColor: ["#0A1929", "#0A1929", "#16373e"],
    tabBarBackgroundColor: "#2D2D2D",
    safeAreaBackgroundColor: "#0A1929",
    headerBackgroundColor: "#0A1929",
    greenDecorationDotColor: "transparent",
    blackDecorationDotColor: "transparent",
    textColor: "white",
    greyTextColor: "white",
    backButtonColor: "white",
    cardBackgroundColor: "#282828",
    cardShadowColor: "#000000",
    categoryTagBackgroundColor: "#F0FFF0",
    nextButtonColor: "#C4C4C4",
  },
};
