export const ScreensName = {
  signup: "signup",
  signin: "signin",
  changePassword: "changePassword",
  verifyEmail: "verifyEmail",
  favorAndSuggest: "favorAndSuggest",
  favorList: "favorList",
  welcome: "welcome",
  home: "Home",
  list: "list",
  search: "search",
  setting: "setting",
  notification: "notification",
  message: "message",
  heartBeat: "heartBeat",
  mealPlan: "mealPlan",
  profile: "profile",
};