export const ScreensName = {
  signup: "signup",
  signin: "signin",
  changePassword: "changePassword",
  resetPassword: "resetPassword",
  verifyEmail: "verifyEmail",
  favorAndSuggest: "favorAndSuggest",
  favorList: "favorList",
  welcome: "welcome",
  home: "Home",
  list: "list",
  search: "search",
  setting: "setting",
  survey: "survey",
  forYou: "forYou",
  notification: "notification",
  message: "message",
  mealPlan: "mealPlan",
  payment: "payment",
  paymentStatus: "paymentStatus",
  profile: "profile",
};
